apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonaria-edge
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: sonaria-edge
  targetNamespace: default
  interval: 1m0s
  chart:
    git: git@github.com:gitsar-global/flux-demo.git
    path: helm-charts/sonaria-edge
    ref: sonaria-edge